version: '3.8'
services:
  
  digital.database:
    image: postgres:latest
    container_name: digital.database
    environment:
      - 'POSTGRES_DB=digitalcard'
      - 'POSTGRES_PASSWORD=server'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 10s
  
  carteiras-digitais.api:
    image: ${DOCKER_REGISTRY-}carteirasdigitaisapi
    build:
      context: .
      dockerfile: Carteiras-Digitais/Dockerfile
    depends_on:
      digital.database:
        condition: service_healthy
    environment:
      - 'DB_HOST=digital.database'
      - 'DB_PORT=5432'
      - 'DB_USER=postgres'
      - 'DB_PASSWORD=server'
      - 'DB_NAME=digitalcard'
    ports:
      - '5000:5000'
  
  

  

